# Generated by Django 5.2.1 on 2025-07-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='view_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='تعداد بازدید'),
        ),
    ]
