# Generated by Django 5.2.1 on 2025-10-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_trackingcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingcode',
            name='tracking_post_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
