# Generated by Django 5.2.1 on 2025-10-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_trackingcode_tracking_post_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_post_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='TrackingCode',
        ),
    ]
