# Generated by Django 5.2.1 on 2025-05-29 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.DecimalField(decimal_places=3, max_digits=15)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('release_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('condition', models.CharField(choices=[('new', 'نو'), ('used', 'استوک')], default='new', max_length=10)),
                ('cleanliness_grade', models.CharField(choices=[('A+', 'A+ (در حد نو)'), ('A', 'A (بسیار تمیز)'), ('B', 'B (تمیز با خط و خش جزئی)'), ('C', 'C (خط و خش مشخص)'), ('D', 'D (دارای آسیب\u200cهای ظاهری)')], default='A', max_length=20)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brand')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor_brand', models.CharField(max_length=50)),
                ('processor_model', models.CharField(max_length=100)),
                ('processor_generation', models.CharField(blank=True, max_length=20)),
                ('ram', models.CharField()),
                ('storage', models.CharField(max_length=30)),
                ('gpu_brand', models.CharField(max_length=50)),
                ('gpu_model', models.CharField(max_length=100)),
                ('gpu_memory', models.CharField(blank=True, max_length=20)),
                ('display', models.CharField(max_length=30)),
                ('battery', models.CharField(max_length=50)),
                ('os', models.CharField(max_length=100)),
                ('keyboard_backlight', models.BooleanField(default=False)),
                ('ports', models.TextField(blank=True)),
                ('weight', models.CharField(max_length=20)),
                ('dimensions', models.CharField(blank=True, max_length=100)),
                ('wifi', models.CharField(blank=True, max_length=50)),
                ('bluetooth', models.CharField(blank=True, max_length=50)),
                ('webcam', models.CharField(blank=True, max_length=50)),
                ('speakers', models.CharField(blank=True, max_length=100)),
                ('laptop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
