# Generated by Django 5.2.1 on 2025-06-02 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cleanliness_grade',
            field=models.CharField(blank=True, choices=[('A+', 'A+ (در حد نو)'), ('A', 'A (بسیار تمیز)'), ('B', 'B (تمیز با خط و خش جزئی)'), ('C', 'C (خط و خش مشخص)'), ('D', 'D (دارای آسیب\u200cهای ظاهری)')], default='A', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='productspecs',
            name='laptop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_specs', to='products.product'),
        ),
    ]
