# Generated by Django 5.2.1 on 2025-06-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_cleanliness_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cleanliness_grade',
            field=models.CharField(blank=True, choices=[('A0', ' (دستگاه آکبند می باشد)'), ('A+', 'A+ (در حد نو)'), ('A', 'A (بسیار تمیز)'), ('B', 'B (تمیز با خط و خش جزئی)'), ('C', 'C (خط و خش مشخص)'), ('D', 'D (دارای آسیب\u200cهای ظاهری)')], default='A', max_length=20, null=True),
        ),
    ]
