# Generated by Django 5.2.1 on 2025-06-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_cleanliness_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
