# Generated by Django 5.2.1 on 2025-07-05 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='laptop',
            new_name='product',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
    ]
